//! spn.lock lockfile parser and generator.
//!
//! The lockfile captures exact resolved versions for reproducible installs.
//!
//! TODO(v0.16): Integrate with `spn install --frozen` for reproducible builds
//!
//! # Example
//!
//! ```toml
//! # spn.lock - DO NOT EDIT (generated by spn install)
//! version = 1
//!
//! [[package]]
//! name = "@workflows/dev-productivity/code-review"
//! version = "1.0.0"
//! source = "registry+https://registry.supernova.sh"
//! checksum = "sha256:abc123..."
//!
//! [[package]]
//! name = "@nika/seo-audit"
//! version = "0.1.5"
//! source = "registry+https://registry.supernova.sh"
//! checksum = "sha256:def456..."
//! dependencies = ["@community/mock-mcp"]
//! ```

#![allow(dead_code)]

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Errors that can occur when working with lockfiles.
#[derive(Error, Debug)]
pub enum LockfileError {
    #[error("Failed to read lockfile: {0}")]
    ReadError(#[from] std::io::Error),

    #[error("Failed to parse lockfile TOML: {0}")]
    ParseError(#[from] toml::de::Error),

    #[error("Failed to serialize lockfile: {0}")]
    SerializeError(#[from] toml::ser::Error),

    #[error("Lockfile not found at: {0}")]
    NotFound(String),

    #[error("Lockfile version {0} not supported (expected {1})")]
    UnsupportedVersion(u32, u32),
}

/// Current lockfile format version.
pub const LOCKFILE_VERSION: u32 = 1;

/// Default registry source URL.
pub const DEFAULT_REGISTRY: &str = "registry+https://registry.supernova.sh";

/// A resolved package in the lockfile.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ResolvedPackage {
    /// Full package name (e.g., "@workflows/dev-productivity/code-review").
    pub name: String,

    /// Exact resolved version.
    pub version: String,

    /// Source registry URL.
    #[serde(default = "default_source")]
    pub source: String,

    /// SHA256 checksum of the tarball.
    pub checksum: String,

    /// Direct dependencies (package names).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

fn default_source() -> String {
    DEFAULT_REGISTRY.to_string()
}

impl ResolvedPackage {
    /// Create a new resolved package.
    pub fn new(name: &str, version: &str, checksum: &str) -> Self {
        Self {
            name: name.to_string(),
            version: version.to_string(),
            source: DEFAULT_REGISTRY.to_string(),
            checksum: checksum.to_string(),
            dependencies: Vec::new(),
        }
    }

    /// Create with dependencies.
    pub fn with_dependencies(mut self, deps: Vec<String>) -> Self {
        self.dependencies = deps;
        self
    }

    /// Create with custom source.
    pub fn with_source(mut self, source: &str) -> Self {
        self.source = source.to_string();
        self
    }
}

/// The spn.lock lockfile structure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SpnLockfile {
    /// Lockfile format version.
    pub version: u32,

    /// Resolved packages (sorted by name for deterministic output).
    #[serde(default, rename = "package")]
    pub packages: Vec<ResolvedPackage>,
}

impl Default for SpnLockfile {
    fn default() -> Self {
        Self::new()
    }
}

impl SpnLockfile {
    /// Create an empty lockfile.
    pub fn new() -> Self {
        Self {
            version: LOCKFILE_VERSION,
            packages: Vec::new(),
        }
    }

    /// Load lockfile from a file path.
    pub fn from_file<P: AsRef<Path>>(path: P) -> Result<Self, LockfileError> {
        let path = path.as_ref();
        if !path.exists() {
            return Err(LockfileError::NotFound(path.display().to_string()));
        }
        let content = std::fs::read_to_string(path)?;
        Self::from_str(&content)
    }

    /// Parse lockfile from a TOML string.
    pub fn from_str(content: &str) -> Result<Self, LockfileError> {
        let lockfile: SpnLockfile = toml::from_str(content)?;

        // Validate version
        if lockfile.version != LOCKFILE_VERSION {
            return Err(LockfileError::UnsupportedVersion(
                lockfile.version,
                LOCKFILE_VERSION,
            ));
        }

        Ok(lockfile)
    }

    /// Find the lockfile in the current directory or .spn/ subdirectory.
    pub fn find_in_dir<P: AsRef<Path>>(dir: P) -> Result<Self, LockfileError> {
        let dir = dir.as_ref();

        // Check .spn/spn.lock first
        let spn_dir_path = dir.join(".spn").join("spn.lock");
        if spn_dir_path.exists() {
            return Self::from_file(&spn_dir_path);
        }

        // Check spn.lock in root
        let root_path = dir.join("spn.lock");
        if root_path.exists() {
            return Self::from_file(&root_path);
        }

        Err(LockfileError::NotFound(format!(
            "No spn.lock found in {} or .spn/",
            dir.display()
        )))
    }

    /// Serialize lockfile to TOML string.
    pub fn to_toml(&self) -> Result<String, LockfileError> {
        // Sort packages for deterministic output
        let mut lockfile = self.clone();
        lockfile.packages.sort_by(|a, b| a.name.cmp(&b.name));

        let toml = toml::to_string_pretty(&lockfile)?;

        // Add header comment
        let header = "# spn.lock - DO NOT EDIT (generated by spn install)\n\n";
        Ok(format!("{}{}", header, toml))
    }

    /// Write lockfile to a file.
    pub fn write_to_file<P: AsRef<Path>>(&self, path: P) -> Result<(), LockfileError> {
        let toml = self.to_toml()?;
        std::fs::write(path, toml)?;
        Ok(())
    }

    /// Add or update a resolved package.
    pub fn add_package(&mut self, package: ResolvedPackage) {
        // Remove existing entry if present
        self.packages.retain(|p| p.name != package.name);
        self.packages.push(package);
    }

    /// Remove a package from the lockfile.
    pub fn remove_package(&mut self, name: &str) -> Option<ResolvedPackage> {
        if let Some(pos) = self.packages.iter().position(|p| p.name == name) {
            Some(self.packages.remove(pos))
        } else {
            None
        }
    }

    /// Get a package by name.
    pub fn get_package(&self, name: &str) -> Option<&ResolvedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Check if a package is in the lockfile.
    pub fn has_package(&self, name: &str) -> bool {
        self.packages.iter().any(|p| p.name == name)
    }

    /// Get all packages as a map for quick lookup.
    pub fn packages_map(&self) -> BTreeMap<&str, &ResolvedPackage> {
        self.packages.iter().map(|p| (p.name.as_str(), p)).collect()
    }

    /// Number of packages in the lockfile.
    pub fn len(&self) -> usize {
        self.packages.len()
    }

    /// Check if lockfile is empty.
    pub fn is_empty(&self) -> bool {
        self.packages.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_empty_lockfile() {
        let lockfile = SpnLockfile::new();
        assert_eq!(lockfile.version, LOCKFILE_VERSION);
        assert!(lockfile.packages.is_empty());
    }

    #[test]
    fn test_add_package() {
        let mut lockfile = SpnLockfile::new();
        let pkg = ResolvedPackage::new("@workflows/code-review", "1.0.0", "sha256:abc123");
        lockfile.add_package(pkg);

        assert_eq!(lockfile.len(), 1);
        assert!(lockfile.has_package("@workflows/code-review"));
    }

    #[test]
    fn test_package_with_dependencies() {
        let pkg = ResolvedPackage::new("@nika/seo-audit", "0.1.5", "sha256:def456")
            .with_dependencies(vec!["@community/mock-mcp".to_string()]);

        assert_eq!(pkg.dependencies.len(), 1);
        assert_eq!(pkg.dependencies[0], "@community/mock-mcp");
    }

    #[test]
    fn test_serialize_to_toml() {
        let mut lockfile = SpnLockfile::new();
        lockfile.add_package(ResolvedPackage::new(
            "@workflows/code-review",
            "1.0.0",
            "sha256:abc123",
        ));

        let toml = lockfile.to_toml().unwrap();
        assert!(toml.contains("# spn.lock - DO NOT EDIT"));
        assert!(toml.contains("version = 1"));
        assert!(toml.contains("[[package]]"));
        assert!(toml.contains("@workflows/code-review"));
    }

    #[test]
    fn test_parse_from_toml() {
        let toml = r#"
version = 1

[[package]]
name = "@workflows/code-review"
version = "1.0.0"
source = "registry+https://registry.supernova.sh"
checksum = "sha256:abc123"

[[package]]
name = "@nika/seo-audit"
version = "0.1.5"
source = "registry+https://registry.supernova.sh"
checksum = "sha256:def456"
dependencies = ["@community/mock-mcp"]
"#;

        let lockfile = SpnLockfile::from_str(toml).unwrap();
        assert_eq!(lockfile.version, 1);
        assert_eq!(lockfile.packages.len(), 2);

        let seo = lockfile.get_package("@nika/seo-audit").unwrap();
        assert_eq!(seo.version, "0.1.5");
        assert_eq!(seo.dependencies.len(), 1);
    }

    #[test]
    fn test_update_existing_package() {
        let mut lockfile = SpnLockfile::new();
        lockfile.add_package(ResolvedPackage::new("@pkg/a", "1.0.0", "sha256:old"));
        lockfile.add_package(ResolvedPackage::new("@pkg/a", "1.0.1", "sha256:new"));

        assert_eq!(lockfile.len(), 1);
        let pkg = lockfile.get_package("@pkg/a").unwrap();
        assert_eq!(pkg.version, "1.0.1");
        assert_eq!(pkg.checksum, "sha256:new");
    }

    #[test]
    fn test_remove_package() {
        let mut lockfile = SpnLockfile::new();
        lockfile.add_package(ResolvedPackage::new("@pkg/a", "1.0.0", "sha256:a"));
        lockfile.add_package(ResolvedPackage::new("@pkg/b", "2.0.0", "sha256:b"));

        let removed = lockfile.remove_package("@pkg/a");
        assert!(removed.is_some());
        assert_eq!(removed.unwrap().name, "@pkg/a");
        assert_eq!(lockfile.len(), 1);
        assert!(!lockfile.has_package("@pkg/a"));
    }

    #[test]
    fn test_deterministic_output() {
        let mut lockfile = SpnLockfile::new();
        // Add in reverse order
        lockfile.add_package(ResolvedPackage::new("@z/last", "1.0.0", "sha256:z"));
        lockfile.add_package(ResolvedPackage::new("@a/first", "1.0.0", "sha256:a"));

        let toml = lockfile.to_toml().unwrap();

        // @a/first should come before @z/last in output
        let pos_a = toml.find("@a/first").unwrap();
        let pos_z = toml.find("@z/last").unwrap();
        assert!(pos_a < pos_z, "Packages should be sorted alphabetically");
    }

    #[test]
    fn test_unsupported_version() {
        let toml = "version = 999\n";
        let result = SpnLockfile::from_str(toml);
        assert!(matches!(
            result,
            Err(LockfileError::UnsupportedVersion(999, 1))
        ));
    }
}
